#!/bin/bash
# Beekeep launcher script

# Get the directory containing this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Set up library search paths
export DYLD_LIBRARY_PATH="$DIR/../Frameworks:$DYLD_LIBRARY_PATH"
export DYLD_FALLBACK_LIBRARY_PATH="$DIR/../Frameworks:/usr/lib:/usr/local/lib"

# Launch the real binary
exec "$DIR/Beekeep_binary" "$@"
